blueprint:
  name: Transition to Scene
  description: >-
    A script to transition to a scene
  domain: script
  source_url: https://github.com/nateprat/homeassistant-blueprints/blob/main/scene_transitions.yaml
  input:
    target_scene:
      name: Scene(s) to activate
      description: Which scene(s) are being activated
      selector:
        entity:
          domain: scene
    transition_period:
      name: Transition period
      description: How long should the transition to activate the scene be
      default: 3
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: seconds
          mode: slider
          step: 0.5

mode: queued

variables:
  target_scene: !input target_scene
  transition_period: !input transition_period

sequence:
  - alias: "Activate scene"
  - service: scene.turn_on
    data:
      transition: !input transition_period
    target:
      entity_id: !input target_scene